-- Create the receipts table
CREATE TABLE public.receipts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  receipt_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL, -- or TEXT if you aren't using Supabase Auth strictly
  payer_name TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  receipt_date DATE NOT NULL,
  payment_mode TEXT,
  description TEXT,
  village TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Fix: Enable Row Level Security (RLS) and allow all operations so you can insert data
ALTER TABLE public.receipts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all operations for now" ON public.receipts;
CREATE POLICY "Allow all operations for now" ON public.receipts FOR ALL USING (true) WITH CHECK (true);

-- Create the receipts bucket for storing PDFs
insert into storage.buckets (id, name, public) 
values ('receipts', 'receipts', true)
on conflict (id) do nothing;

-- Allow public access to the bucket
create policy "Public Access" on storage.objects for all using ( bucket_id = 'receipts' );
